#!/bin/bash
# genconf.sh NAME PORT [DIR]
if [ $# -lt 2 ] || [ $# -gt 3 ]; then
  echo "Usage: $(basename "$0") NAME PORT [DIR]" >&2
  exit 1
fi
NAME=$1 PORT=$2 DIR=${3:-$HOME/conf}
[[ $NAME =~ ^[a-z][a-z0-9_-]*$ ]] || { echo "Error: invalid name '$NAME'" >&2; exit 2; }
if [[ ! $PORT =~ ^[0-9]+$ ]] || [ "$PORT" -lt 1024 ] || [ "$PORT" -gt 64535 ]; then
  echo "Error: invalid port '$PORT'" >&2
  exit 3
fi
FILE="$DIR/$NAME.conf"
[ -e "$FILE" ] && { echo "Error: $FILE already exists" >&2; exit 4; }

if [ ! -d "$DIR" ]; then
  mkdir -p "$DIR" || exit 5
  echo "Created directory $DIR"
fi
cat > "$FILE" << EOF
# $NAME.conf - generated by genconf.sh for $USER
[service]
name = "$NAME"
port = $PORT
admin_port = $((PORT + 1000))
[paths]
log = \$LOGDIR/$NAME.log
data = ~/data/$NAME
[run]
start = \`which $NAME\` --port=$PORT
match = \\d+ 'quoted' "double"
EOF
echo "Wrote $FILE ($(wc -l < "$FILE") lines)"
