#!/bin/bash
N=$(ls datos | wc -l)
cat > saluda.sh << EOF
#!/bin/bash
# generated by $USER in $(pwd)
# datos had $N entries when this script was generated
echo "Hello, \$1"
echo "You gave me \$# arguments"
EOF
chmod +x saluda.sh
./saluda.sh "$(cat nombre.txt)" extra

